import { StyleSheet } from 'react-native';
import { theme } from '../../theme/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.backgroundLight,
    },
    header: {
        paddingTop: 48,
        paddingHorizontal: 24,
        paddingBottom: 24,
        backgroundColor: theme.colors.white,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(19, 236, 19, 0.1)',
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: 16,
    },
    settingsBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(19, 236, 19, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileInfo: {
        alignItems: 'center',
    },
    avatarContainer: {
        position: 'relative',
        marginBottom: 16,
    },
    avatarBorder: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 4,
        borderColor: theme.colors.primary,
        backgroundColor: theme.colors.borderLight,
    },
    avatar: {
        width: '100%',
        height: '100%',
    },
    verifiedBadge: {
        position: 'absolute',
        bottom: 4,
        right: 4,
        backgroundColor: theme.colors.primary,
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: theme.colors.white,
        alignItems: 'center',
        justifyContent: 'center',
    },
    name: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.colors.textDark,
    },
    bio: {
        fontSize: 14,
        color: theme.colors.textLight,
        marginBottom: 24,
        marginTop: 4,
    },
    statsContainer: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
    },
    statBox: {
        flex: 1,
        backgroundColor: theme.colors.white,
        borderWidth: 1,
        borderColor: 'rgba(19, 236, 19, 0.1)',
        borderRadius: 16,
        padding: 12,
        alignItems: 'center',
        marginHorizontal: 8,
        elevation: 2,
        shadowColor: theme.colors.primary,
        shadowOpacity: 0.1,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
    },
    statValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.colors.primary,
    },
    statLabel: {
        fontSize: 10,
        fontWeight: '600',
        color: theme.colors.textLight,
        letterSpacing: 1,
        marginTop: 4,
    },
    content: {
        padding: 24,
        paddingBottom: 100,
    },
    tabsWrapper: {
        flexDirection: 'row',
        backgroundColor: 'rgba(19, 236, 19, 0.05)',
        borderRadius: 30,
        padding: 4,
        marginBottom: 32,
    },
    tabActive: {
        flex: 1,
        backgroundColor: theme.colors.primary,
        borderRadius: 24,
        paddingVertical: 12,
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
    },
    tabInactive: {
        flex: 1,
        borderRadius: 24,
        paddingVertical: 12,
        alignItems: 'center',
    },
    tabTextActive: {
        color: theme.colors.white,
        fontWeight: 'bold',
        fontSize: 14,
    },
    tabTextInactive: {
        color: theme.colors.textLight,
        fontWeight: '600',
        fontSize: 14,
    },
    collectionsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    collectionsTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.textDark,
    },
    addCollectionBtn: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    addCollectionText: {
        color: theme.colors.primary,
        fontWeight: '600',
        fontSize: 14,
        marginLeft: 4,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    collectionCard: {
        width: '48%',
        marginBottom: 16,
    },
    collectionImgWrapper: {
        width: '100%',
        aspectRatio: 1,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 8,
        borderWidth: 1,
        borderColor: 'rgba(19, 236, 19, 0.05)',
    },
    collectionImg: {
        width: '100%',
        height: '100%',
    },
    collectionOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.1)',
        justifyContent: 'flex-end',
        padding: 8,
    },
    collectionBadge: {
        backgroundColor: 'rgba(255,255,255,0.9)',
        alignSelf: 'flex-start',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    collectionBadgeText: {
        fontSize: 10,
        fontWeight: 'bold',
        color: theme.colors.textDark,
        letterSpacing: 0.5,
    },
    collectionTitle: {
        fontWeight: 'bold',
        fontSize: 14,
        color: theme.colors.textDark,
    },
    createCollectionCard: {
        width: '48%',
        aspectRatio: 1,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: 'rgba(19, 236, 19, 0.3)',
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        marginBottom: 16,
    },
    createCollectionText: {
        fontSize: 12,
        fontWeight: '600',
        color: 'rgba(19, 236, 19, 0.6)',
        marginTop: 8,
    }
});
