import { StyleSheet, Platform } from 'react-native';
import { theme } from '../../theme/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.backgroundLight,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.colors.backgroundLight,
    },
    headerBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingBottom: 16,
        backgroundColor: 'rgba(246, 248, 246, 0.9)',
        zIndex: 10,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: theme.colors.white,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    headerActions: {
        flexDirection: 'row',
    },
    headerActionButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: theme.colors.white,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
        marginLeft: 12,
    },
    scrollContent: {
        paddingBottom: 40,
    },
    coverImage: {
        width: '100%',
        height: 300,
        resizeMode: 'cover',
    },
    titleSection: {
        padding: 24,
        backgroundColor: theme.colors.white,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.borderLight,
        marginBottom: 8,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: theme.colors.textDark,
        marginBottom: 16,
        lineHeight: 34,
    },
    metaInfo: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.backgroundLight,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        marginRight: 12,
        marginBottom: 8,
    },
    metaText: {
        fontSize: 14,
        color: theme.colors.textLight,
        marginLeft: 4,
        fontWeight: '500',
    },
    section: {
        padding: 24,
        backgroundColor: theme.colors.white,
        marginBottom: 8,
    },
    lastSection: {
        marginBottom: 0,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: theme.colors.textDark,
        marginBottom: 16,
    },
    ingredientItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    ingredientDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.colors.primary,
        marginTop: 8,
        marginRight: 12,
    },
    ingredientQuantity: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.textDark,
        width: 80,
    },
    ingredientName: {
        flex: 1,
        fontSize: 16,
        color: theme.colors.textDark,
        lineHeight: 24,
    },
    instructionStep: {
        flexDirection: 'row',
        marginBottom: 20,
    },
    stepNumberContainer: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
        marginTop: 2,
    },
    stepNumber: {
        color: theme.colors.white,
        fontWeight: 'bold',
        fontSize: 14,
    },
    stepText: {
        flex: 1,
        fontSize: 16,
        color: theme.colors.textDark,
        lineHeight: 24,
    },
    commentItem: {
        backgroundColor: theme.colors.backgroundLight,
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
    },
    commentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    commentUser: {
        fontWeight: 'bold',
        color: theme.colors.textDark,
        fontSize: 14,
    },
    commentDate: {
        color: theme.colors.textLight,
        fontSize: 12,
    },
    commentText: {
        color: theme.colors.textDark,
        fontSize: 14,
        lineHeight: 20,
    },
    emptyText: {
        color: theme.colors.textLight,
        fontSize: 14,
        fontStyle: 'italic',
    }
});
